import os
import time
import marko

BR = "<br><br>"

antal = 0

def writeHtmlFile(filename, content=""):
	index = 1 + filename.rindex("\\")
	short_md = filename[index:].replace('.html','.md')
	long_md = filename.replace('.html','.md')
	global antal

	res = []
	res.append('<!-- Generated by makeAll.py 1.0 -->')
	res.append('<html>')
	res.append('<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />')
	res.append('<head>')
	res.append('	<meta charset = "utf-8"/>')
	res.append("	<style> body { font-family:monospace; font-size:20px } </style>")
	res.append("	<style> a { text-decoration: none; background-color: #ff8 } </style>")
	res.append('</head>')
	res.append('<body>')
	res += [content]
	res.append('</body>')
	if os.path.exists(long_md):
		res.append('<footer style=" text-align: right">')
		res.append(f'	<p><a href="{short_md}">markdown</a></p>')
		res.append("</footer>")
	res.append('</html>')

	print(short_md, '=>', filename)
	antal += 1
	with open(filename, 'w', encoding='utf8') as g:
		g.write('\n'.join(res))

def title(s): return f"<h1>{s.replace('.md','')}</h1>"

def noExt(s): return s.replace(".pdf", "").replace(".md", "").replace("_", " ")

def transpileDir(directory):

	if type(directory) is str:
		path = directory
		name = directory
	else:
		path = directory.path
		name = directory.name

	if name == 'files': return

	name = name.replace("_", " ")
	res = []

	indexHtml = ""

	for f in os.scandir(path):
		if os.path.isfile(f):
			if f.name.endswith('.html'):
				pass
			elif f.name.endswith('index.md'):
				indexHtml = transpileFile(f.path)
			elif f.name.endswith('.md'):
				filename = f.path.replace('.md', '.html')
				writeHtmlFile(filename, title(f.name) + transpileFile(f.path))
				res += [f"<a href='{f.name.replace('.md', '.html')}'>{f.name.replace('.md', '')}</a>" + BR + "\n"]
			else:
				res += [f"<a href='{f.name}'>{noExt(f.name)}</a>" + BR + "\n"]
		else:
			if f.name != 'files':
				res += [f"<a href='{f.name}\\index.html'>{f.name}</a>" + BR + "\n"]
				transpileDir(f)

	if indexHtml == "":
		indexHtml = "\n".join(res)
	else:
		indexHtml = indexHtml.replace("CONTENT","\n".join(res))

	writeHtmlFile(path + '\\index.html', title(name) + indexHtml)

def transpileFile(filename):
	with open(filename,encoding='utf8') as f:
		html = marko.convert(f.read())
		html = html.replace('<red>',  '<div style=color:#F00>').replace('</red>','</div>')
		html = html.replace('<green>','<div style=color:#0A0>').replace('</green>','</div>')
		return html

start = time.time_ns()

transpileDir("Seniorschack_Stockholm")

print(antal, 'files took', round((time.time_ns() - start)/10**6),'ms')
