import os
import time
import markdown
from markdown.extensions.tables import TableExtension

# Innebär att Startbilden påverkas. Kanske behövs ett kommando i .md-filen a la CONTENT. NEWS?
# RSS

file_count = 0
md_bytes = 0
html_bytes = 0

settings = {
	'rootFolder': "Seniorschack_Stockholm",
	'showExt': False,
	'latestNews': 5,
}

def writeHtmlFile(filename, title, level, content=""):
	index = 1 + filename.rindex("\\")
	short_md = filename[index:].replace('.html','.md')
	long_md = filename.replace('.html','.md')
	global file_count
	global html_bytes

	res = []
	res.append('<!-- Generated by makeAll.py 1.0 -->')
	res.append('<html>')
	res.append('	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />')
	res.append('	<head>')
	res.append(f'		<title>{title}</title>')
	res.append('		<meta charset = "utf-8"/>')
	res.append('		<link href="' + level * '../' + 'style.css" rel="stylesheet" type="text/css" >')
	res.append('	</head>')
	res.append('<body>')
	res += [f"<h1>{title}</h1>"]

	res += [content]

	if os.path.exists(long_md):
		res.append('<div style=" text-align: right">')
		res.append(f'	<a href="{short_md}">markdown</a> {level}')
		res.append("</div>")
	else:
		res.append('<div style=" text-align: right">')
		res.append(f'	{level}')
		res.append("</div>")

	res.append('</body>')
	res.append('</html>')

	print(short_md, '=>', filename)
	file_count += 1
	with open(filename, 'w', encoding='utf8') as g:
		s = '\n'.join(res)
		g.write(s)
		html_bytes += len(s)

def title(s): return s.replace('.md','')

def noExt(s):
	s = s.replace("_", " ")
	if settings['showExt']: return s
	else: return s.replace(".pdf", "").replace(".md", "").replace(".xls", "")

def getLink(filename):
	with open(filename,encoding='utf8') as f: return f.read().strip()

def getNews(directory=settings["rootFolder"] + "/files/news"):
	files = os.listdir(directory)
	files = files[: -settings["latestNews"]: -1]
	res = [f"<div><a href='files/news/{f}'>{noExt(f)}</a></div>" for f in files]
	return "\n".join(res)

def transpileDir(directory,level=0):

	if type(directory) is str:
		path = directory
		name = directory
	else:
		path = directory.path
		name = directory.name

	if name == 'files' or name.endswith('.css'): return

	name = name.replace("_", " ")
	res = []

	indexHtml = ""

	for f in os.scandir(path):
		if os.path.isfile(f):
			if f.name.endswith('.html') or f.name.endswith('.css'):
				pass
			elif f.name.endswith('index.md'):
				indexHtml = transpileFile(f.path)
			elif f.name.endswith('.md'):
				filename = f.path.replace('.md', '.html')
				writeHtmlFile(filename, title(f.name), level, transpileFile(f.path))
				res += [f"<div><a href='{f.name.replace('.md', '.html')}'>{f.name.replace('.md', '')}</a></div>"]
			elif f.name.endswith('.link'):
				res += [f"<div><a href='{getLink(f.path)}'>{f.name.replace('.link', '')}</a></div>"]
			else:
				res += [f"<div><a href='{f.name}'>{noExt(f.name)}</a></div>"]
		else:
			if f.name != 'files':
				res += [f"<div><a href='{f.name}\\index.html'>{f.name}</a></div>"]
				transpileDir(f,level+1)

	if indexHtml == "":
		indexHtml = "\n".join(res)
	else:
		indexHtml = indexHtml.replace("CONTENT","\n".join(res))
		indexHtml = indexHtml.replace("NEWS",news)

	writeHtmlFile(path + '\\index.html', title(name), level, indexHtml)

def patch(s): # Reason: To have some whitespace between links (margin-bottom)
	s = s.replace('<p><a href=','<div><a href=')
	s = s.replace('</a></p>','</a></div>')
	return s

def transpileFile(filename):
	global md_bytes

	with open(filename,encoding='utf8') as f:
		md = f.read()
		html = markdown.markdown(md,extensions=[TableExtension(use_align_attribute=True)])
		html = patch(html)
		md_bytes += len(md)
	return html

start = time.time_ns()
news = getNews()
transpileDir(settings['rootFolder'],0)
print(md_bytes,'=>',html_bytes,'bytes')
print(file_count, 'files took', round((time.time_ns() - start)/10**6),'ms')
